[tool.ruff]
# 启用所有推荐规则
select = ["E", "F", "W", "I", "B", "C4", "ARG", "SIM"]
ignore = []

# 允许自动修复
fixable = ["ALL"]
unfixable = []

# 排除某些目录
exclude = [
    ".git",
    ".venv",
    "node_modules",
    "venv",
    ".env",
    "build",
    "dist",
]

# 行长度设置
line-length = 100

# 允许未使用的变量以下划线开头
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.isort]
known-third-party = ["streamlit", "pandas", "numpy", "matplotlib", "seaborn"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.pylint.messages_control]
disable = [
    "C0111", # 缺少文档字符串
    "C0103", # 变量命名不符合命名规范
    "C0303", # 行尾空格
    "W1201", # 在日志中使用%格式化
    "W1202", # 在日志中使用format格式化
]

[tool.pylint.format]
max-line-length = 100

[tool.pylint.design]
max-args = 6
max-attributes = 12
max-branches = 12
max-locals = 15
min-public-methods = 1
max-public-methods = 20
max-returns = 6 